version: '3.5'

services:
  db:
    image: postgres:11.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=development
      - APP_NAME=tcc-api
    volumes:
      - .:/usr/src/app
    depends_on:
      - db